2022 12 19 bootstrap
FATMAP/gha-file-sync pull request #1
Opened 2022-12-20 16:37 UTC by SlevinWasAlreadyTaken

2022-12-22 12:05 UTC, tbmetcalfe commented
Just wanted to add a note - hitting an API limit with the current setup. Perhaps we can resolve this issue in this PR. Or perhaps I'll make an issue instead to be addressed later.

2023-03-31 12:30 UTC, SlevinWasAlreadyTaken commented on internal/github/helpers.go
> +// GetRepoUrl based on given parameters
```suggestion
```

2023-04-03 13:49 UTC, svenjr approved these changes

2023-04-03 13:49 UTC, svenjr commented on Dockerfile
> +FROM golang:1.20 as builder
You can also use the FATMAP Go image if you want

```suggestion
FROM 793842381218.dkr.ecr.eu-west-1.amazonaws.com/fatmap-golang:v1.20.0 as builder
```

2023-04-03 13:49 UTC, svenjr commented on Dockerfile
> +LABEL maintainer="github.com/SlevinWasAlreadyTaken"
```suggestion
LABEL maintainer="platform@fatmap.com"
```

2023-04-03 13:49 UTC, svenjr commented on README.md
> +Github Action for Cross-Repos Files Synchronization using Pull Requests.
```suggestion
Github Action for Cross-Repo Files Synchronization using Pull Requests.
```

2023-04-03 13:49 UTC, svenjr commented on internal/cfg/config.go
> +		"\n\tIs GitHub token set?", (len(c.GithubToken) != 0),
nit - can ignore
```suggestion
		"\n\tGitHub token set?", (len(c.GithubToken) != 0),
```

2023-04-03 13:49 UTC, svenjr commented on internal/cfg/config.go
> +// InitConfig based on env variables
We follow linting based [here](https://github.com/FATMAP/avalanche-bulletin-service/blob/main/.golangci.yml) which includes using a period (`.`) at the end of comments. I will leave it up to SRE to decide but this is generally the linting and structure we follow for Go inside the mapping team
```suggestion
// InitConfig based on env variables.
```

I won't make a comment for each of these instances but just mention it once

2023-04-03 13:49 UTC, svenjr commented on internal/cfg/config.go
> +	}
```suggestion
	// auto-truncate pr title - 80 characters maximum
	if len(prTitle) > 80 {
		prTitle = prTitle[:79]
	}
```
80 or 100 characters?

2023-04-03 13:49 UTC, svenjr commented on internal/git/repository.go
> +}
nit - I would break these into other structs for clarity but not required. If I find myself demarcating structs by comments, I usually do this.

```suggestion
type Repository struct {
	git         gitConfig
	auth        authConfig
	internal    internalState
}

// gitConfig contains the repository configuration relating to git.
type gitConfig struct {
	syncBranchName string
	repoURL        string
	localPath      string
}

// authConfig contains the repository configuration for auth.
type authConfig struct {
	auth       *http.BasicAuth
	authorName string
}

type internalState struct {
	baseBranchName string // main or master
	repo           *git.Repository
	workTree       *git.Worktree
	syncRef        *plumbing.Reference
}
```

2023-04-03 13:49 UTC, svenjr commented on internal/git/repository.go
> +		All:  true,
Does this blindly add all files in the local directory?

2023-04-03 13:49 UTC, svenjr commented on internal/git/repository.go
> +	// return true of status return a non empty result
```suggestion
	// Return true if statuses is non-zero.
```

2023-04-03 13:49 UTC, svenjr commented on internal/git/repository.go
> +	}
Nit: maybe move the `a` and `b` comments to just above the logic they relate to

2023-04-03 13:49 UTC, svenjr commented on internal/github/client.go
> +	if err != nil {
```suggestion
// GetAuthenticatedUsername returns the username of the current authenticated user
func (c Client) GetAuthenticatedUsername(ctx context.Context) (string, error) {
    // empty string makes the library return the authenticated user
	user, _, err := c.Client.Users.Get(ctx, "") 
	if err != nil {
```

2023-04-03 13:49 UTC, svenjr commented on internal/sync/manager.go
> +		return fmt.Errorf("create repo manager: %v", err)
```suggestion
		return fmt.Errorf("creating sync task: %v", err)
```

2023-04-03 13:49 UTC, svenjr commented on internal/sync/manager.go
> +	t, err := NewTask(
`t` should be `task` for clarity

2023-04-03 13:49 UTC, svenjr commented on internal/sync/manager.go
> +		return fmt.Errorf("has changed: %v", err)
```suggestion
		return fmt.Errorf("checking for changes: %v", err)
```

2023-04-03 13:49 UTC, svenjr commented on internal/sync/task.go
> +	mygit "github-file-sync/internal/git"
package should not be renamed here - `git` is fine

2023-04-03 13:49 UTC, svenjr commented on internal/sync/task.go
> +// Task is a handler which synchronize a git repository files on github with current filesystem and given rules called file bindings
```suggestion
// Task is a handler which synchronizes a git repository files on github with current filesystem and given rules called file bindings
```

2023-04-03 13:49 UTC, svenjr commented on internal/sync/task.go
> +	return t, nil
```suggestion
	return t, err
```

2023-04-03 13:50 UTC, svenjr commented on Dockerfile
> +FROM golang:1.20 as builder
Ignore this if it will be open-source

2023-04-03 13:57 UTC, SlevinWasAlreadyTaken commented on Dockerfile
> +FROM golang:1.20 as builder
It is supposed to be open-source so I will stick to the vanilla go image :)

2023-04-03 14:01 UTC, SlevinWasAlreadyTaken commented on internal/sync/manager.go
> +	t, err := NewTask(
done in 30e84411e2c8903c3f4c3e298a0060224f99fc7b

2023-04-03 14:02 UTC, SlevinWasAlreadyTaken commented on internal/sync/task.go
> +	mygit "github-file-sync/internal/git"
done in 0cc4d087f71f5c2282ccbc7194097e6154d19793

2023-04-03 14:28 UTC, SlevinWasAlreadyTaken commented on internal/cfg/config.go
> +// InitConfig based on env variables
- I've copied/pasted the `.golang-ci.yml` file locally and applied most of the comment aside:
    - `fieldalignment` which I don't care about (I prefer structure readability over performances here).
    - `gomnd`: I don't want to declare static int here - it is less readable to me.
    - `gocritic`: telling me I don't document exported function when I actually do it, just not the way the rule expects it.

2023-04-24 11:29 UTC, tbmetcalfe requested changes
Just want to resolve the error message I get with the Makefile, otherwise looks good.

2023-04-24 11:29 UTC, tbmetcalfe commented on .tool-versions
> +make 4.2.1
Set golang version?

2023-04-24 11:29 UTC, tbmetcalfe commented on Makefile
> +	go build &&	./github-file-sync
I get this error message:

```
level=INFO msg=Configuration...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x110c7fd]

goroutine 1 [running]:
github-file-sync/internal/cfg.InitConfig()
	<BASE_PATH>/gha-file-sync/internal/cfg/config.go:31 +0x1d
main.main()
	<BASE_PATH>/gha-file-sync/main.go:21 +0x54
```

2023-04-24 13:20 UTC, SlevinWasAlreadyTaken commented on Makefile
> +	go build &&	./github-file-sync
Fixed in c925841eb3865f58e91019c425a7db1f7d9e6dea, my bad

2023-04-24 13:21 UTC, SlevinWasAlreadyTaken commented on .tool-versions
> +make 4.2.1
👍 fixed in 994d9f9fdd1215cf13b9720180e30a696437bddc

2023-04-24 14:20 UTC, tbmetcalfe approved these changes

2023-04-24 15:32 UTC, SlevinWasAlreadyTaken commented on internal/git/repository.go
> +}
discussed orally.
It is nice to do but I prefer for now to keep a simpler structure

2023-04-25 10:53 UTC, merged